CREATE DATABASE db;

CREATE TABLE IF NOT EXISTS employee
( id INTEGER NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);


